INSERT INTO tb_category(name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Smartphones', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Tablets', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Accessories', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Home Appliances', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Audio & Video', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Gaming', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Furniture', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Clothing', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Shoes', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Sports & Fitness', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Beauty & Health', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Toys & Hobbies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Office Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Automotive', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Garden & Outdoor', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Pet Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Groceries', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Jewelry', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Watches', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Bags & Luggage', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Baby Products', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Kitchenware', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Lighting', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Musical Instruments', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Cameras & Photography', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Health Care Devices', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Cleaning Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Stationery', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Art & Crafts', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Industrial Tools', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Safety Equipment', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Construction Materials', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Travel & Tourism', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Movies & Entertainment', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Collectibles', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Board Games & Puzzles', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Energy & Utilities', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Pharmaceuticals', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Medical Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Food & Beverages', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Software & Apps', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Virtual Products', NOW());